### PR TITLE
Move setup environment scripts to meta-mbl

### PR DESCRIPTION
**Pull request by jjohnson-arm**
To allow customers to fork mbl-config and change bblayers without losing the
latest setup environment changes - i.e. less need to keep up to date with
our mbl-config.

### CODE REVIEW

**Comment by jjohnson-arm** [comment]
Question - should we also move the bblayers files for the BSPs into meta-mbl?

**Comment by jonathanhaigh-arm** [comment]
> Question - should we also move the bblayers files for the BSPs into meta-mbl?

I started thinking about that when I saw your PRs.I think we should move them. I was also wondering whether the mechanism to include the correct BSP bblayers file should also live in meta-mbl; that would probably just be a one line file containing
```
include bblayers_##MACHINE##.conf
```
And then we'd have to update `setup-environment-internal` to do `##MACHINE##` replacement in this new file.

That layer of indirection would be useful if we later wanted to have e.g. DISTRO specific layers too and for users to pick up the mechanism for that automatically... I'm not yet convinced it's worth it though.

Aside: should that really be `include` or should it be `require`? For the default MBL build I think it should be `require` - we'd want the build to fail if the BSP bblayers file couldn't be found... When customers use the line when building with a BSP not provided by MBL, do we want to force them to create a new MACHINE bblayers file? It's not a big deal but it would be one more thing to thing to do when setting up a project (and another thing to document).

**Comment by diego-sueiro** [comment]
I agree with the suggestion to move the `bblayers_${MACHINE}.conf` files to `meta-mbl` and I think we should move everything. Doesn't make sense to maintain this repo with only the `bblayers.conf` and `local.conf` file.

**Comment by jjohnson-arm** [comment]
Understood - agree with moving them - will move to meta-mbl/meta-mbl-bsp-common/conf

**Pull request merged**
